### ISSUE TITLE
Custom Bitrate not shown in UI, when loaded from profile

### ISSUE THREAD

**Issue by E-t-z** [cdgriffith/FastFlix#165]
When you create custom profile, for example Bitrate 16000k, 
it will revert to lowest available (500k) in UI if you reload that profile later.

In YAML, it seems to have stored correct value though.

```
    x264:
      bitrate: 16000k
      crf: null
      extra: ''
      max_muxing_queue_size: '1024'
      pix_fmt: yuv420p
      preset: slower
      profile: default
      tune: null
    x265: null

```
In my opinion, UI should show actual configured values, in this case Custom and 16000k

Now when you load that profile, and Add that job to queue, it will apply lowest possible value 500k and will encode with it.
